server:
  port: 8001

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092

  redis:
    host: localhost
    port: 6379
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: health, info, redis
