server:
  port: 8001

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

spring.main.allow-bean-definition-overriding: true
